### ISSUE TITLE
Don't append slash to url if it already exists

### ISSUE THREAD

**Issue by d1skort** [cf-platform-eng/concourse-pypi-resource#10]
Hello! 

First of all, I want to say thank you for this resource ;)

I have some problem here:

After uploading package to pypi I get this error:
```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://nexus.devbg.us/repository/pypi-staging//fly/json
```

My resource configuration:
```
  - name: pypi-package
    type: pypi
    source:
      name: fly
      username: ((twine_username))
      password: ((twine_password))
      repository_url: https://nexus.devbg.us/repository/pypi-staging/
```

Ok, I remove trailing slash, but now I even can't upload package:
```
HTTPError: 400 Client Error: Repository path must have another '/' after initial '/' for url: https://nexus.devbg.us/repository/pypi-staging
```

I think problem is in function `get_pypi_package_info`:
```
url = get_pypi_url(input) + '/' + package_name + '/json'
```
